version: '3.5'

services:
  postgres:
    container_name: postgres_container_lab
    image: postgres:17.4-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres_lab:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres_lab
    restart: unless-stopped

networks:
  postgres_lab:
    driver: bridge

volumes:
    postgres_lab: